"""
Django settings for CaelusDB_project project.

Generated by 'django-admin startproject' using Django 4.x
"""

import os
from pathlib import Path
import dj_database_url  # Důležité pro Render

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- DŮLEŽITÁ BEZPEČNOSTNÍ NASTAVENÍ ---

# SECURITY WARNING: keep the secret key used in production secret!
# Pro Render.com toto nastavíte v "Environment Variables"
SECRET_KEY = os.environ.get('SECRET_KEY', 'default_local_secret_key_pro_vyvoj')

# SECURITY WARNING: don't run with debug turned on in production!
# Render automaticky nastaví DEBUG na False, pokud najde proměnnou RENDER.
DEBUG = 'RENDER' not in os.environ

# Nastavení serverů, které mohou hostovat vaši aplikaci
ALLOWED_HOSTS = []

# Render automaticky přidá vaši *.onrender.com doménu sem
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# --- NASTAVENÍ APLIKACÍ ---

# Aplikace, které jsou součástí vašeho projektu
INSTALLED_APPS = [
    # Django aplikace
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Vaše aplikace (kde máte models.py)
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CaelusDB_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Pro HTML šablony na úrovni projektu
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CaelusDB_project.wsgi.application'


# --- DATABÁZE (NASTAVENO PRO RENDER.COM) ---

# Výchozí databáze je SQLite (pro lokální vývoj)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Toto je "magie" pro Render:
# Pokud program běží na Renderu (kde najde proměnnou 'DATABASE_URL'),
# automaticky přepíše 'default' databázi na produkční PostgreSQL.
# Lokálně bude stále používat SQLite.
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        ssl_require=True  # Render vyžaduje SSL
    )


# --- SPRÁVA UŽIVATELŮ (VÁŠ VLASTNÍ MODEL) ---

# Toto je klíčový řádek, který říká Djangu, aby použilo váš model
# místo výchozího.
AUTH_USER_MODEL = 'main.Uzivatele'


# --- VALIDACE HESEL ---

AUTH_PASSWORD_VALIDATORS = [
    {
        # Heslo nesmí být podobné jménu nebo e-mailu
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Minimální délka (vychozi 8 znaku)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Nesmí být na seznamu běžných hesel (jako "password", "123456")
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Nesmí se skládat pouze z čísel.
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- LOKALIZACE (JAZYK, ČAS) ---

LANGUAGE_CODE = 'cs-cz'  # Nastaveno na češtinu

TIME_ZONE = 'Europe/Prague'  # Nastaveno na Prahu

USE_I18N = True

USE_TZ = True


# --- STATICKÉ SOUBORY (CSS, JavaScript, Obrázky) ---

STATIC_URL = 'static/'

# Toto je důležité pro Render, aby věděl, kam ukládat statické soubory
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# --- VÝCHOZÍ PRIMÁRNÍ KLÍČ ---

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Po úspěšném přihlášení půjde uživatel na úvodní stránku
LOGIN_REDIRECT_URL = '/'

# Po odhlášení taky (pojistka, kdyby nefungovalo nastavení v urls.py)
LOGOUT_REDIRECT_URL = '/'
