# Generated by Django 5.2.8 on 2025-11-16 13:51

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('kod_iata', models.CharField(max_length=3, unique=True)),
                ('zeme_registrace', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Letiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_letiste', models.CharField(max_length=255)),
                ('kod_iata', models.CharField(max_length=3, unique=True)),
                ('mesto', models.CharField(max_length=100)),
                ('zeme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('cislo_pasu', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_aerolinky', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zamestnanci', to='main.aerolinky')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Letadla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('kapacita_sedadel', models.IntegerField()),
                ('datum_vyroby', models.DateField()),
                ('id_aerolinky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letadla', to='main.aerolinky')),
            ],
        ),
        migrations.CreateModel(
            name='Lety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_letu', models.CharField(max_length=10)),
                ('cas_odletu', models.DateTimeField()),
                ('cas_priletu', models.DateTimeField()),
                ('id_aerolinky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.aerolinky')),
                ('id_letadla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.letadla')),
                ('id_letiste_odletu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odlety', to='main.letiste')),
                ('id_letiste_priletu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prilety', to='main.letiste')),
                ('posadka', models.ManyToManyField(related_name='lety', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_rezervace', models.DateTimeField(auto_now_add=True)),
                ('celkova_cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_platby', models.CharField(choices=[('NEZAPLACENO', 'Nezaplaceno'), ('ZAPLACENO', 'Zaplaceno'), ('STORNOVANO', 'Stornováno')], default='NEZAPLACENO', max_length=20)),
                ('id_uzivatele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleUzivatel',
            fields=[
                ('id_prirazeni', models.AutoField(primary_key=True, serialize=False)),
                ('plati_od', models.DateTimeField(auto_now_add=True)),
                ('plati_do', models.DateTimeField(blank=True, null=True)),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role')),
                ('id_uzivatele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_uzivatele', 'id_role', 'plati_do')},
            },
        ),
        migrations.AddField(
            model_name='uzivatele',
            name='role',
            field=models.ManyToManyField(related_name='uzivatele', through='main.RoleUzivatel', to='main.role'),
        ),
        migrations.CreateModel(
            name='TridySedadel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_tridy', models.CharField(max_length=100)),
                ('popis', models.TextField(blank=True, null=True)),
                ('id_aerolinky', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.aerolinky')),
            ],
        ),
        migrations.CreateModel(
            name='Letenky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_sedadla', models.CharField(max_length=4)),
                ('cena_letenky', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_letu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lety')),
                ('id_rezervace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rezervace')),
                ('id_tridy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tridysedadel')),
            ],
        ),
        migrations.CreateModel(
            name='InventarLetu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet_mist_k_prodeji', models.PositiveIntegerField()),
                ('id_letu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lety')),
                ('id_tridy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tridysedadel')),
            ],
            options={
                'unique_together': {('id_letu', 'id_tridy')},
            },
        ),
    ]
