# Generated by Django 5.2.8 on 2025-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='uzivatele',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='aerolinky',
            name='zeme_registrace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
