# Generated by Django 5.2.8 on 2025-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_uzivatele_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letadla',
            name='kapacita_sedadel',
            field=models.PositiveIntegerField(),
        ),
    ]
