# Generated by Django 5.2.8 on 2025-11-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_letadla_kapacita_sedadel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzivatele',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='uzivatele',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
