# Generated by Django 5.2.8 on 2025-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_uzivatele_first_name_alter_uzivatele_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzivatele',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
