# Generated by Django 5.2.8 on 2025-11-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_uzivatele_first_name_alter_uzivatele_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarletu',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
